#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=5g
#SBATCH --time=00:07:00

module load Bioinformatics mummer/4.0.0rc1
module load R/4.4.0

python dotplot_MODIFY2.py --query to318ko_data/reference/ \
--subject to318ko_data/query/ML2TQ8.fasta \
--name to318ko_v2

