#!/bin/bash

#SBATCH --mail-user=jjhale@umich.edu
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=esnitkin1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=5g
#SBATCH --time=01:00:00

module load Bioinformatics mummer/4.0.0rc1
module load R/4.4.0

# python dotplot.py --query query/MI_KPC_774/ \
# --subject reference/kpc_assemblies/MI_KPC_774_flye_medaka_polypolish.fasta \
# --name kpc_v1 --highlight highlight_data_KPC.tsv

python sloop.py
